// <auto-generated />
using ApiRestASPNETCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiRestASPNETCore.Migrations
{
    [DbContext(typeof(Conexiones))]
    partial class ConexionesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiRestASPNETCore.Models.Vestimenta", b =>
                {
                    b.Property<int>("IdVestimenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVestimenta"));

                    b.Property<bool>("EnvioGratis")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("Precio")
                        .HasPrecision(10)
                        .HasColumnType("real(10)");

                    b.HasKey("IdVestimenta");

                    b.ToTable("Vestimenta", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
